/*
 * Converts the archivist's hand — short handwritten words — to SVG paths
 * (SPEC-EXPERIENCE §3). Run by hand, output committed:
 *
 *   node scripts/name/build-words.mjs
 *
 * Same face and same conversion as the name (./outline.mjs); the face never
 * loads in the browser. These are outlines only. Words that later draw on
 * (ink material) get hand-authored pen strokes the way the name did.
 *
 * Every word shares one vertical frame — the same box height and baseline —
 * so words set at the same font-size are the same size and line up.
 */

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { outline, round4 } from './outline.mjs'

const OUT = fileURLToPath(new URL('../../src/content/hand.ts', import.meta.url))

/* key -> text. Section labels (§2, §5.3) and the cursor's action labels (§6). */
const WORDS = {
  index: 'the index',
  subject: 'subject',
  capability: 'capability',
  correspondence: 'correspondence',
  open: 'open',
  write: 'write',
  visit: 'visit',
}

/* A coarser grid than the name: 100 units to the em is ~0.3px at label size. */
const UNITS = 100

/* Covers Caveat's tallest ascender and deepest descender, with a little air. */
const TOP = -72
const BOTTOM = 24
const SIDE = 2

const entries = Object.entries(WORDS).map(([key, text]) => {
  const { d, box } = outline(text, UNITS)
  const x = Math.floor(box.x1 - SIDE)
  const width = Math.ceil(box.x2 + SIDE) - x
  return `  ${key}: { text: ${JSON.stringify(text)}, viewBox: '${x} ${TOP} ${width} ${BOTTOM - TOP}', d: '${d}' },`
})

const source = `/*
 * GENERATED by scripts/name/build-words.mjs — do not edit by hand.
 * Handwritten words, Caveat 400, ${UNITS} units to the em, baseline at y = 0.
 */

/** Box height in ems of the face — the same for every word. */
export const handHeightEm = ${round4((BOTTOM - TOP) / UNITS)}

/** Baseline as a fraction of the box height, from the top. */
export const handBaseline = ${round4(-TOP / (BOTTOM - TOP))}

export const hand = {
${entries.join('\n')}
} as const

export type HandWord = keyof typeof hand
`

writeFileSync(OUT, source)
console.log(`wrote ${OUT} — ${entries.length} words`)
