/*
 * Converts the name to SVG paths (SPEC §4, §6). Run by hand, not at build:
 *
 *   node scripts/name/build-name.mjs
 *
 * The output, src/content/name.ts, is committed. The browser never loads the
 * handwriting face — it only ever sees these paths — so the font here is a
 * build-time input and nothing more (see styles/fonts.css).
 *
 * Two layers come out of this:
 *   - the glyph outlines, converted from Caveat 400 (filled, marigold);
 *   - the pen strokes, hand-authored in ./strokes.mjs, which are animated and
 *     used as a mask that reveals the outlines as they draw.
 *
 * The outline is exact to the face. The strokes only have to cover it, so a
 * stroke that is slightly off the letter's centre changes nothing visible.
 */

import opentype from 'opentype.js'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { strokes, PEN_WIDTH } from './strokes.mjs'

const here = (file) => fileURLToPath(new URL(file, import.meta.url))

const NAME = 'Prince Agrawal'
const FONT = here('./caveat-latin-400-normal.woff')
const OUT = here('../../src/content/name.ts')

const buf = readFileSync(FONT)
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength))

/* Font units, baseline at y = 0, y pointing down (SVG orientation). */
const path = font.getPath(NAME, 0, 0, font.unitsPerEm, { kerning: true })

const n = (v) => String(Math.round(v))
const outline = path.commands
  .map((c) => {
    switch (c.type) {
      case 'M':
        return `M${n(c.x)} ${n(c.y)}`
      case 'L':
        return `L${n(c.x)} ${n(c.y)}`
      case 'Q':
        return `Q${n(c.x1)} ${n(c.y1)} ${n(c.x)} ${n(c.y)}`
      case 'C':
        return `C${n(c.x1)} ${n(c.y1)} ${n(c.x2)} ${n(c.y2)} ${n(c.x)} ${n(c.y)}`
      case 'Z':
        return 'Z'
    }
  })
  .join('')

/*
 * Pen strokes: point lists in the same units, smoothed into cubic curves
 * (Catmull-Rom). Each one is timed by its length so the pen moves at one
 * speed throughout — a long stroke takes longer, as it would by hand.
 */
function smooth(points) {
  let d = `M${points[0][0]} ${points[0][1]}`
  for (let i = 0; i < points.length - 1; i++) {
    const p0 = points[i - 1] ?? points[i]
    const p1 = points[i]
    const p2 = points[i + 1]
    const p3 = points[i + 2] ?? p2
    const c1 = [p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6]
    const c2 = [p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6]
    d += `C${c1.map(Math.round).join(' ')} ${c2.map(Math.round).join(' ')} ${p2.join(' ')}`
  }
  return d
}

function length(points) {
  let total = 0
  for (let i = 1; i < points.length; i++) {
    total += Math.hypot(points[i][0] - points[i - 1][0], points[i][1] - points[i - 1][1])
  }
  return total
}

const lengths = strokes.map(length)
const total = lengths.reduce((a, b) => a + b, 0)
let at = 0
const timed = strokes.map((points, i) => {
  const start = at / total
  at += lengths[i]
  return { d: smooth(points), start: round4(start), span: round4(lengths[i] / total) }
})

function round4(v) {
  return Math.round(v * 1e4) / 1e4
}

/* The box covers both layers, with the pen's half-width as margin. */
const box = path.getBoundingBox()
const margin = PEN_WIDTH / 2
const xs = strokes.flat().map((p) => p[0])
const ys = strokes.flat().map((p) => p[1])
const x1 = Math.floor(Math.min(box.x1, ...xs) - margin)
const y1 = Math.floor(Math.min(box.y1, ...ys) - margin)
const x2 = Math.ceil(Math.max(box.x2, ...xs) + margin)
const y2 = Math.ceil(Math.max(box.y2, ...ys) + margin)

const source = `/*
 * GENERATED by scripts/name/build-name.mjs — do not edit by hand.
 * "${NAME}", Caveat 400, font units (${font.unitsPerEm}/em), baseline at y = 0.
 */

export const nameViewBox = '${x1} ${y1} ${x2 - x1} ${y2 - y1}'

/** Baseline position as a fraction of the box height, for aligning with text. */
export const nameBaseline = ${round4(-y1 / (y2 - y1))}

/** Box height in ems of the face, so the SVG can be sized from a type token. */
export const nameHeightEm = ${round4((y2 - y1) / font.unitsPerEm)}

export const nameOutline = '${outline}'

export const penWidth = ${PEN_WIDTH}

/** start and span are fractions of the whole draw. */
export const nameStrokes: ReadonlyArray<{ d: string; start: number; span: number }> = ${JSON.stringify(timed, null, 2)}
`

writeFileSync(OUT, source)
console.log(`wrote ${OUT} — ${strokes.length} strokes, viewBox ${x1} ${y1} ${x2 - x1} ${y2 - y1}`)
