/*
 * Image conversion (SPEC §10, SPEC-EXPERIENCE §8 E1). Run by hand:
 *
 *   node scripts/images/build-images.mjs
 *
 * Originals live in images-src/, which is not deployed. Everything in
 * public/ ships, so only the converted sizes go there. Budget: under 400 KB
 * for every image file the site ships, all sizes and formats together. The
 * script prints the total and fails if it is over.
 *
 * Writes public/images/* and src/content/images.ts (committed).
 */

import sharp from 'sharp'
import { mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const here = (file) => fileURLToPath(new URL(file, import.meta.url))
const SRC = here('../../images-src/')
const OUT = here('../../public/images/')
const MANIFEST = here('../../src/content/images.ts')
const BUDGET = 400 * 1024

/*
 * Both photos show in the Subject plate, which is at most 18rem wide — 288px,
 * so 576px at 2x. 360 and 720 cover 1x and 2x+ with room to spare.
 */
const IMAGES = [
  { name: 'portrait', file: 'prince-portrait.jpeg', widths: [360, 720] },
  { name: 'childhood', file: 'childhood-photo.jpg', widths: [360, 720] },
]

const FORMATS = [
  { ext: 'avif', type: 'image/avif', apply: (img) => img.avif({ quality: 50, effort: 6 }) },
  { ext: 'webp', type: 'image/webp', apply: (img) => img.webp({ quality: 72, effort: 6 }) },
]

rmSync(OUT, { recursive: true, force: true })
mkdirSync(OUT, { recursive: true })

const manifest = {}
for (const image of IMAGES) {
  const meta = await sharp(SRC + image.file).metadata()
  const sources = {}
  for (const format of FORMATS) {
    const entries = []
    for (const width of image.widths) {
      const out = `${image.name}-${width}.${format.ext}`
      await format.apply(sharp(SRC + image.file).rotate().resize({ width })).toFile(OUT + out)
      entries.push(`/images/${out} ${width}w`)
    }
    sources[format.type] = entries.join(', ')
  }
  const largest = image.widths.at(-1)
  manifest[image.name] = {
    sources,
    src: `/images/${image.name}-${largest}.webp`,
    width: largest,
    height: Math.round((largest * meta.height) / meta.width),
  }
}

let total = 0
for (const file of readdirSync(OUT)) {
  const size = statSync(OUT + file).size
  total += size
  console.log(`${(size / 1024).toFixed(1).padStart(7)} KB  ${file}`)
}
console.log(`${(total / 1024).toFixed(1).padStart(7)} KB  total (budget ${BUDGET / 1024} KB)`)

writeFileSync(
  MANIFEST,
  `/*
 * GENERATED by scripts/images/build-images.mjs — do not edit by hand.
 * Responsive sources for the site's photographs. width/height are the
 * largest size, for the aspect ratio; srcset and sizes pick the file.
 */

export type ResponsiveImage = {
  sources: { [type: string]: string }
  src: string
  width: number
  height: number
}

export const images = ${JSON.stringify(manifest, null, 2)} satisfies { [name: string]: ResponsiveImage }
`,
)

if (total > BUDGET) {
  console.error('Over the image budget.')
  process.exit(1)
}
