/*
 * GENERATED by scripts/images/build-images.mjs — do not edit by hand.
 * Responsive sources for the site's photographs. width/height are the
 * largest size, for the aspect ratio; srcset and sizes pick the file.
 */

export type ResponsiveImage = {
  sources: { [type: string]: string }
  src: string
  width: number
  height: number
}

export const images = {
  "portrait": {
    "sources": {
      "image/avif": "/images/portrait-360.avif 360w, /images/portrait-720.avif 720w",
      "image/webp": "/images/portrait-360.webp 360w, /images/portrait-720.webp 720w"
    },
    "src": "/images/portrait-720.webp",
    "width": 720,
    "height": 1044
  },
  "childhood": {
    "sources": {
      "image/avif": "/images/childhood-360.avif 360w, /images/childhood-720.avif 720w",
      "image/webp": "/images/childhood-360.webp 360w, /images/childhood-720.webp 720w"
    },
    "src": "/images/childhood-720.webp",
    "width": 720,
    "height": 960
  }
} satisfies { [name: string]: ResponsiveImage }
